config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]

    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージがありません'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader
  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :group_users
         has_many :groups,  through: :group_users
         has_many :messages

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @messages = Message.where('id>?', params[:id])
    respond_to do |format|
      format.html 
      format.json 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group,only:[:edit,:update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json 
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %ii= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    /
      <div class='chat-group-form__field--left'>
      <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
      </div>
      <div class='chat-group-form__field--right'>
      <div class='chat-group-form__search clearfix'>
      <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
      </div>
      <div id='user-search-result'></div>
      </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div id='chat-group-users'>
        <div class='chat-group-user clearfix' id='chat-group-user-22'>
        <input name='chat_group[user_ids][]' type='hidden' value='22'>
        <p class='chat-group-user__name'>seo_kyohei</p>
        </div>
        </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      -# %input.chat-group-form__action-btn{"data-disable-with":"Save", name: "commit", type: "submit", value: "Save"}/
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/_side_bar.html.haml
.chat-side
  .side-header
    %p.side-header__use-name<
      = current_user.name
    %ul.user-menu
      %li.user-menu__new-group
        = link_to new_group_path do
          =fa_icon "edit", class: 'icon-color'
      %li.user-menu__edit-user<
        = link_to edit_user_registration_path(current_user) do
          =fa_icon "cog", class: 'icon-color'
          
  .groups
    - current_user.groups.each do |group|
      =link_to group_messages_path(group) ,class: 'group' do
        .group__group-name<
          = group.name
        .group__latest-message<
          = group.show_last_message

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals:{group: @group}

app/views/groups/index.html.haml
= render 'side_bar'
-# = render 'messages/message'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group}

app/views/layouts/_flash.html.haml
.flash
  - flash.each do |key,value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks: { track: true }}
    = javascript_include_tag 'application', data: { turbolinks: { track: true }}
    = csrf_meta_tags
  %body
    = render partial: 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.message{data:{id: message.id}}
  .upper-info
    %p.upper-info__user
      = message.user.name
    %p.upper-info__date
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  %p.message__text
    - if message.content.present?
      = message.content
    = image_tag message.image.url, class:'message__text__image' if message.image.present?

app/views/messages/index.html.haml
= render "groups/side_bar"

.chat-main
  .main-header
    .current-group
      %h2.current-group__name
        = @group.name
      %ul.member-list
        Member：
        %li.member-list__member
          - @group.users.each do |user|
            = user.name

    =link_to 'Edit', edit_group_path(@group),class: 'main-header__edit-btn'

  .messages
    = render @messages

  .form
    = form_for [@group, @message] do |f|
      .new-message
        .new-message__box
          = f.text_field :content, class:'new-message__box__text', placeholder: "type a message"
          = f.label :image, class: 'new-message__box__image' do
            = fa_icon 'image', class: 'icon' 
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'new-message__submit'